repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black gmail_auto_forwarding/
        language: system
        always_run: true
        pass_filenames: false
      - id: isort
        name: isort
        entry: poetry run isort gmail_auto_forwarding/
        language: system
        always_run: true
        pass_filenames: false
      - id: flake8
        name: flake8
        entry: poetry run flake8 gmail_auto_forwarding/
        language: system
        always_run: true
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: poetry run mypy gmail_auto_forwarding/
        language: system
        always_run: true
        pass_filenames: false
      - id: create-requirements-txt
        name: create-requirements-txt
        entry: poetry export -f requirements.txt --output requirements.txt --without-hashes
        language: system
        always_run: true
        pass_filenames: false
